Handle unimplemented reporting features
SuperGoodSoft/solidus_taxjar pull request #141
Opened 2022-01-05 18:54 UTC by benjaminwil

What is the goal of this PR?
---

**Stop errorring out when an order without `OrderTransaction`s is marked as shipped.**

If Solidus TaxJar's reporting functionality is enabled, and an order is shipped, the `Solidus::Event#shipment_shipped` event that fires causes an error. This is because we were not rescuing from the `StandardError` that notified end users that a reporting feature had not yet been implemented.

This error was unexpected and not handled gracefully. Until the reporting functionality has been completed, we want the `#shipment_shipped` event to *do nothing* if it hits an unimplemented feature's codepath.

How do you manually test these changes? (if applicable)
---

1. In the Solidus admin, mark an order as shipped.
    * [ ] Watch the order shipment state change to "shipped".
    * [ ] Do not get redirected to a `StandardError` page.

Merge Checklist
---

- [ ] Run the manual tests
- [ ] Update the changelog
- [ ] Run a sandbox app and verify taxes are being calculated

2022-01-05 19:12 UTC, forkata approved these changes

2022-01-05 19:40 UTC, Noah-Silvera approved these changes

2022-01-06 02:06 UTC, jarednorman requested changes

2022-01-06 16:50 UTC, benjaminwil commented
Fixed a typo and rebased against `master`.

2022-01-13 22:46 UTC, jarednorman approved these changes

2022-01-14 18:22 UTC, merged