Add basic UI for Taxjar settings in solidus admin
SuperGoodSoft/solidus_taxjar pull request #37
Opened 2021-02-08 22:55 UTC by Noah-Silvera

This commit adds a tab to the taxes section of the solidus admin settings. 
This provides the foundation for further configuration of Taxjar through the solidus admin.

Right now, the new settings tab simply displays your Taxjar API key that you supply when booting the app.

<img width="987" alt="Screen Shot 2021-02-08 at 14 54 05PST" src="https://user-images.githubusercontent.com/8933450/107291775-88ffe680-6a1d-11eb-8201-283b0ba33ac9.png">

2021-02-08 22:58 UTC, Noah-Silvera commented
Drafting as this PR is missing tests

2021-02-22 05:00 UTC, Noah-Silvera commented
This PR is currently based on top of #39 so the first two commits can be ignored.

2021-02-22 23:02 UTC, jarednorman requested changes
"TaxJar" has a capital "J" and they probably care about that for certification purposes. 😅

2021-02-23 00:23 UTC, Noah-Silvera commented
> "TaxJar" has a capital "J" and they probably care about that for certification purposes. 😅

You are correct, they do, I will correct this! I got confused by the PR to rename the modules to use a lowercase J haha.

2021-02-23 03:09 UTC, jarednorman commented
That was to avoid fighting with Zeitwerk, though I'd prefer keeping the correct naming if it's not too difficult to support that from an extension.

2021-02-23 16:26 UTC, Noah-Silvera commented
> That was to avoid fighting with Zeitwerk, though I'd prefer keeping the correct naming if it's not too difficult to support that from an extension.

One easy way to avoid fighting Zeitwerk would be to rename all the files/folders that are currently `solidus_taxjar` to `solidus_tax_jar`, which would translate to a camelized `SolidusTaxJar` in zeitwork land.

What do you think of that?

The other option (I think) would be asking users to [globally add zeitwork infections](https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#customizing-inflections) for our project, which I am less of a fan of. I tried doing a big of digging, but I haven't found an examples of adding an initializer to an extension like this. I can do some more digging and asking around.

2021-02-25 01:00 UTC, jarednorman commented
I think it's probably worth renaming all the folders. That's going to be less of a pain for people upgrading. That won't play nice with @AdnanTheExcellent's work over on #32, though.

2021-03-02 00:19 UTC, nvandoorn commented
Referring to @jarednorman's comment above, as per discussion in #32, the folders will not be renamed to align with the TaxJar gem.

2021-03-02 01:04 UTC, Noah-Silvera commented
@jarednorman this is ready for a re-review!

2021-03-09 20:38 UTC, jarednorman approved these changes

2021-03-22 17:53 UTC, nvandoorn approved these changes

2021-03-22 20:56 UTC, adammathys approved these changes

2021-03-29 16:55 UTC, jarednorman approved these changes

2021-05-12 23:05 UTC, jarednorman approved these changes

2021-05-12 23:05 UTC, jarednorman commented
I look forward to the day I stop getting notifications about this PR.

2021-05-17 22:40 UTC, merged