Support order_recalculated event in Solidus < 2.11
SuperGoodSoft/solidus_taxjar pull request #80
Opened 2021-06-09 19:22 UTC by nvandoorn

What is the goal of this PR?
---

Support order_recalculated event in Solidus < 2.11

How do you manually test these changes? (if applicable)
---

1. Load the sandbox app
    * [ ] Verify the decorator is loaded

Merge Checklist
---

- [ ] Run the manual tests
- [ ] Update the changelog
- [ ] Run a sandbox app and verify taxes are being calculated

2021-06-09 20:49 UTC, jarednorman approved these changes

2021-06-09 20:58 UTC, jarednorman approved these changes

2021-06-16 18:54 UTC, adammathys requested changes
There are quite a few spec failures that at a quick glance look to be related to this work.

2021-06-16 21:57 UTC, Noah-Silvera commented
> There are quite a few spec failures that at a quick glance look to be related to this work.

Thanks Adam! It was a namespacing problem introduced by the decorator.

2021-06-17 16:02 UTC, adammathys approved these changes

2021-06-21 22:43 UTC, merged